### ISSUE TITLE
spatial enhence cross_attention

### ISSUE THREAD

**Issue by yunfeiheng** [rshaojimmy/SeqDeepFake#4]
Hello, I am currently studying this paper. I don't quite understand the spatial enhanced cross-attention module in the code. Regarding the calculation of spatial center and scale, is it for each different tampering sequence? In other words, the spatial center and scale on the face are different for different tampering order. Also, I am not very clear about the meaning of some variables in the code, such as point1, 2, 3, and point_sigmoid_ref_inter and point_sigmoid_ref. Could you please explain them to me?

**Comment by mamarasulovs** [comment]
> Recently, I have been studying this paper and I am not very clear about formula 4 in the paper. The spatial weight map M is generated for each type of manipulation operation. Therefore, if there are several annotations in the manipulation sequence, there should be several M. So, in formula 4, M should be the sum of all M for each operation of each input? I am not very clear about this calculation.

write down by wechat :sms9299

**Comment by islimeng** [comment]
i have a configuration quesion but i cannot reslove it,would someone can help me?

Traceback (most recent call last):
  File "D:/seqdeepfake/SeqDeepFake/train.py", line 435, in <module>
    cfg = Config(args.cfg)
  File "D:\seqdeepfake\SeqDeepFake\models\configuration.py", line 6, in __init__
    with open(config_file) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
